"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path  # นำเข้า Path เพื่อจัดการเส้นทางไฟล์

# กำหนดเส้นทางโฟลเดอร์หลักของโปรเจกต์
BASE_DIR = Path(__file__).resolve().parent.parent

# การตั้งค่าที่เหมาะสำหรับการพัฒนา ไม่แนะนำสำหรับ production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jgzz8p4^@q(4p53yqp4twi%zd*v^2@h0@etx0_e9@gy4ti+nn4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # ควรตั้งเป็น False ใน production

ALLOWED_HOSTS = []  # รายชื่อ host ที่อนุญาตให้เชื่อมต่อ (production ต้องกำหนดค่า)

# Application definition

INSTALLED_APPS = [
    # แอปพลิเคชันที่ติดตั้งไว้ล่วงหน้า
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # แอปของคุณ
    'sensorapp',  # เพิ่มแอป sensorapp ของโปรเจกต์
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'  # กำหนดให้ Django ใช้ไฟล์ urls.py ของโปรเจกต์

# การตั้งค่าเทมเพลต
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # กำหนดการใช้ Django Templates
        'DIRS': [BASE_DIR / 'sensorapp/templates'],  # เพิ่มเส้นทางโฟลเดอร์เทมเพลต
        'APP_DIRS': True,  # ให้ Django ค้นหาเทมเพลตในแต่ละแอปโดยอัตโนมัติ
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'  # กำหนด WSGI สำหรับโปรเจกต์นี้

# Database
# การตั้งค่า database SQLite ซึ่งเป็นฐานข้อมูลเริ่มต้นของ Django
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # ใช้ฐานข้อมูล SQLite
        'NAME': BASE_DIR / 'db.sqlite3',  # ไฟล์ฐานข้อมูลจะถูกเก็บไว้ใน BASE_DIR
    }
}

# Password validation
# ตัวกรองความปลอดภัยของรหัสผ่านสำหรับการตรวจสอบความปลอดภัย
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# การตั้งค่าเกี่ยวกับภาษาของระบบ
LANGUAGE_CODE = 'en-us'  # ภาษาหลักคืออังกฤษ (สหรัฐอเมริกา)
TIME_ZONE = 'UTC'  # โซนเวลาเป็น UTC
USE_I18N = True  # เปิดใช้การแปลภาษา
USE_TZ = True  # ใช้การตั้งค่าโซนเวลา

# Static files (CSS, JavaScript, Images)
# การตั้งค่าสำหรับการจัดการไฟล์ static เช่น CSS และรูปภาพ
STATIC_URL = '/static/'  # URL สำหรับไฟล์ static

# เพิ่มตำแหน่งโฟลเดอร์ static ของโปรเจกต์ (ถ้ามี)
STATICFILES_DIRS = [
    BASE_DIR / "sensorapp/static",  # โฟลเดอร์ static ที่ระดับโปรเจกต์
]

# Default primary key field type
# การตั้งค่าประเภทของ primary key field เป็นค่าเริ่มต้น
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
